### ISSUE TITLE
AE2 Storage Provider loop

### ISSUE THREAD

**Issue by spannerman79** [jredfox/confighelper#13]
`evilnotchlib-a109.jar` & `confighelper-1.2.4.8.jar`
MC 1.7.10

`conflicts.json` showed the following;

```
{
  "providers-id:4": [
    {
      "name": "Storage Cell",
      "mod": "Applied Energistics 2",
      "class": "appeng.spatial.StorageWorldProvider"
    },
    {
      "name": "Storage Cell",
      "mod": "Applied Energistics 2",
      "freeId": 3,
      "class": "appeng.spatial.StorageWorldProvider"
    }
  ]
}
```

Then when I change the provider to 3, to cycles back to the following;

```
{
  "providers-id:3": [
    {
      "name": "Storage Cell",
      "mod": "Applied Energistics 2",
      "class": "appeng.spatial.StorageWorldProvider"
    },
    {
      "name": "Storage Cell",
      "mod": "Applied Energistics 2",
      "freeId": 4,
      "class": "appeng.spatial.StorageWorldProvider"
    }
  ]
}
```

This is a never ending loop

The only way I can get around this is adding `appeng.spatial.StorageWorldProvider` to `S:conflicts`

**Comment by jredfox** [comment]
ok so this is what's called a self conflict. Input the class `appeng.spatial.StorageWorldProvider` into self conflicts. This is evidence of a broken mod instantiating a new world provider with the same id without unregistering the first one this is not config helpers problem however self conflicts will resolve your issue. 

I can't autodetect self conflicts cause sometimes they are wrapper classes or have multiple objects inside of them like biomes.
