### ISSUE TITLE
[1.7.10] Crash when any potion effect is applied to any entity

### ISSUE THREAD

**Issue by aking4125** [jredfox/confighelper#27]
Hello,

Unsure if this is related to this or EvilNotchLib. But, after a successful adjustment of all IDs. Upon loading a world either in Single Player or on a Dedicated server. The Client crashes as soon as it detects any entity within the player radius or the player itself has any Potion effect applied to it. 

[crash-2022-05-02_06.39.38-client.txt](https://github.com/jredfox/confighelper/files/8602331/crash-2022-05-02_06.39.38-client.txt)

Removing this mod and EvilNotchLib _then switching to the below mods_ fixes the problem. 

For Enchantment IDs, I use this [mod](https://www.curseforge.com/minecraft/mc-mods/enchantment-id-extender).
For Potion IDs, I use this [mod](https://www.curseforge.com/minecraft/mc-mods/extended-potions).
For all other IDs, I use this [mod](https://www.curseforge.com/minecraft/mc-mods/endlessids) (In conjunction with Config Helper _or_ the above two)

Note that the above mods are only used as an _Alternative_ to ID extending. They are not loaded simultaneously.

Any ideas?

**Comment by jredfox** [comment]
don't use https://www.curseforge.com/minecraft/mc-mods/enchantment-id-extender
don't use https://www.curseforge.com/minecraft/mc-mods/extended-potions
don't use https://www.curseforge.com/minecraft/mc-mods/endlessids
config helper already does all of this. these mods are conflicting

**Comment by jredfox** [comment]
@aking4125 also java.lang.NoSuchMethodError: net.minecraft.network.play.server.S1DPacketEntityEffect.func_149425_g()S was the cause not what you said on those mods. this is caused by a mod expecting `java.lang.NoSuchMethodError: net.minecraft.network.play.server.S1DPacketEntityEffect.func_149425_g()S` to be there when it's now `java.lang.NoSuchMethodError: net.minecraft.network.play.server.S1DPacketEntityEffect.func_149425_g()I`

**Comment by aking4125** [comment]
>config helper already does all of this. these mods are conflicting

1. Removing EndlessIDs causes the ID limit to be reached. Config Helper doesn't cover block IDs correctly as the client crashes claiming it hit a block ID limit. 

2. Enchantment ID Extender and Extended Potions, like I said, are **only used when Config Helper _fails_** with the above issue.

3. **As stated. Removing config helper and EvilNotchLib fixes the problem.**

But I'll take your word for it.

**Comment by jredfox** [comment]
config helper extends both potion and enchantment ids. potion ids are int and enchantment ids are short. enchantment ids shouldn't cause a problem unless a mod reads nbt as getByte.

remove those mods I stated before. I need steps to reproduce with evil notch lib, config helper, and what mod and config is causing this.

**Comment by aking4125** [comment]
> config helper extends both potion and enchantment ids. potion ids are int and enchantment ids are short. enchantment ids shouldn't cause a problem unless a mod reads nbt as getByte.
> 
> remove those mods I stated before. I need steps to reproduce with evil notch lib, config helper, and what mod and config is causing this

Oh boy. You really don't read.

Those mods ARE removed....

**Comment by jredfox** [comment]
you don't read it does extend them. if my mods are removed then the crash is invalid and not mine thanks for waisting my time. enjoy the ban.

**Comment by LightninDud** [comment]
> you don't read it does extend them. if my mods are removed then the crash is invalid and not mine thanks for waisting my time. enjoy the ban.

Bruh.

As stated over and over again. The two mods you seem to be focused on are not apart of the mod list generated in the crash report. Forge has this great feature of outputting all the mods in the crash report. If you do a CTRL+ F and Search for Either Enchantment ID Extender or Extended Potions. You will see both Jar files are not loaded. Only EndlessIDs are there.

On your own [curseforge page](https://www.curseforge.com/minecraft/mc-mods/confighelper). The ID Extensions from Config Helper extend the following:

```
id extensions:
Extend DataWatcher ids from 31 to Integer.MAX_VALUE
Extended DataWatcher Data types from 6 hardcoded to Integer.MAX_VALUE
Extend Potion ids to Integer.MAX_VALUE
Extend Enchantment ids to Short.MAX_VALUE
Extend Entity ids to Integer.MAX_VALUE
```

[EndlessIDs](https://www.curseforge.com/minecraft/mc-mods/endlessids). Extends the Block and Item ID limit. Which Config help doesn't do. As proven by this crash report here, removing EndlessIDs.
[crash-2022-05-02_13.12.20-client.txt](https://github.com/jredfox/confighelper/files/8604870/crash-2022-05-02_13.12.20-client.txt)
 
 Regardless of what the initial report states at the very top. The fact remains:
 
 **Removing Config Helper Fixes the problem.**
 
This report was created so it can be put under investigation. A crash report doesn't have to state which specific mod is crashing. We are only here to report our findings and removing Config Helper, Then replacing Potion and Enchantment ID extensions with the above mod Fixes the problem. Why? We have no idea. But if you think people are wasting your time, so be it. Your choice.

**Comment by jredfox** [comment]
ban evasion won't help you. you are reporting invalid issues. the only valid thing you reported is the crash report then provide a whole bunch of spam that's irrelevant and missleading. and yes you do have to comply with my github rules. I asked you to provide the exact mods needed to reproduce because it didn't happen for me. all you had to do was say hey this x mod with config helper causes a crash with the potion. instead you keep going on invalid issues that don't even exist as well as trolling
